worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    server_tokens off;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 8904;
        server_name $SERVER_UI_NAME;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;

        # Content Security Policy (CSP)
        add_header Content-Security-Policy "
            default-src 'self' blob:;
            connect-src 'self' $CSP_DOMAIN https://exercisedb.p.rapidapi.com https://api.calorieninjas.com;
            script-src 'self' 'unsafe-inline';
            style-src 'self' 'unsafe-inline';
            img-src 'self' data:;
            media-src 'self';
            font-src 'self';
            frame-src 'self' blob:;
        " always;

        # Cache headers (optional but useful)
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 7d;
            add_header Cache-Control "public, no-transform";
        }

        root /var/www/app;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        error_page 404 /index.html;
    }
}
